language: go

go:
 - 1.8.3

matrix:
  fast_finish: true

sudo: false

env:
  global:
   - GOBIN=$HOME/bin
   - PATH=$HOME/bin:$PATH

script:
 - go tool vet -all .
 - go install ./...
 - go test -race -v ./...
